/*
 * This project was created by Donovan Adrian and any
 * edits or changes must be confirmed as valid by Donovan
 * with written consent under any circumstance.
 */
package imagesetorganizer.presentation;
import imagesetorganizer.presentation.ImageSetPickerUI;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Donovan Adrian
 */
public class WelcomeUI extends javax.swing.JFrame {

    /**
     * Creates new form WelcomeUI
     */
    public WelcomeUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        welcomeTextFieldA = new javax.swing.JLabel();
        welcomeTextFieldB = new javax.swing.JLabel();
        bringBackBtn = new javax.swing.JButton();
        resetConfigBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        welcomeTextFieldA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeTextFieldA.setText("Welcome To The Image Set Organizer!");
        welcomeTextFieldA.setAlignmentY(1.0F);
        welcomeTextFieldA.setBounds(new java.awt.Rectangle(0, 0, 45, 16));
        welcomeTextFieldA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        welcomeTextFieldB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeTextFieldB.setText("Choose an option below to begin");
        welcomeTextFieldB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bringBackBtn.setText("Bring Back Photos");
        bringBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bringBackBtnActionPerformed(evt);
            }
        });

        resetConfigBtn.setText("Reset Config");
        resetConfigBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetConfigBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resetConfigBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bringBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(welcomeTextFieldB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(welcomeTextFieldA, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(welcomeTextFieldA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcomeTextFieldB)
                .addGap(24, 24, 24)
                .addComponent(bringBackBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetConfigBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitBtn)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void resetConfigBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetConfigBtnActionPerformed
        boolean userChoice = trueFalsePrompt("Are you sure you want to reset"
                + " the config?", "Are you sure?");
        if (userChoice){
            this.setVisible(false);
            ImageSetPickerUI imageSetPicker = new ImageSetPickerUI();
            imageSetPicker.setVisible(true);
        }
    }//GEN-LAST:event_resetConfigBtnActionPerformed

    private void bringBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bringBackBtnActionPerformed
        ArrayList<File> imageSetFolders = new ArrayList<>();
        ArrayList<File> imageSetFiles = new ArrayList<>();
        ArrayList<File> completedTransfers = new ArrayList<>();
        ArrayList<File> createdFolders = new ArrayList<>();
        ArrayList<String> configMemory = new ArrayList<>();
        Path fileQueuePath;
        File configFile = new File("config.txt");
        File tempImageSetFolder;
        File destinationDirSrc;
        File sourceDirSrc;
        File fileQueue;
        int imageSetNum = 0;
        String sourceDirName = "";
        String transferStatus = "NOMINAL";
        boolean configError = false;
        
        try {
            FileReader fReader = new FileReader(configFile);
            BufferedReader bReader = new BufferedReader(fReader);
            String output = "";
            while((output = bReader.readLine()) != null)
                configMemory.add(output);
            System.out.println("Config Read");
        } catch (IOException ioe) {
            System.out.println("Error: Config Not Read...");
            JOptionPane.showMessageDialog(null,
                "There was an error reading\n"
              + "the config... Please try again!",
                "Failed Reading Config", JOptionPane.ERROR_MESSAGE);
            configError = true;
        }
        
        if (!configError && !configMemory.isEmpty()){
            imageSetNum = Integer.valueOf(configMemory.get(2));
            destinationDirSrc = new File(configMemory.get(3));
            sourceDirSrc = new File(configMemory.get(4));
            
            if (destinationDirSrc.exists() && sourceDirSrc.exists() && imageSetNum != 0)
                System.out.println("All Operations Nominal");
            else if (destinationDirSrc.exists() && !sourceDirSrc.exists() && imageSetNum != 0){
                System.out.println("Source Set Up Required");
                
                //Set Up Source
                
                //Check Print Folders and check Destination Dir for similar names
                    //Only Enable "Smart Sources" After 10 Transfers
                    //Confirm Smart Selection Y/N
                    //Store Y/N
                        //If No, wait 10 more transfers and query source folder
                //Query Source Folder (Dialog -> Directory)
                    //Confirm Selection Y/N
                    
            } else {
                
                //Eventually set up to point back to new directories
                
                System.out.println("Destination Exists: " + destinationDirSrc.exists());
                System.out.println("Source Exists: " + sourceDirSrc.exists());
                System.out.println("Image Set #: " + imageSetNum);
                JOptionPane.showMessageDialog(null,
                    "There was an error reading\n"
                  + "the config... Please try again!",
                    "Failed Reading Config", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            for (final File fileEntry : destinationDirSrc.listFiles())
                if (fileEntry.getName().contains(" - ") && 
                    fileEntry.getName().contains(" Print")){
                    imageSetFolders.add(fileEntry);
                    System.out.println("Added: " + fileEntry.getName());
                }
            
            if (imageSetFolders.isEmpty()){
                JOptionPane.showMessageDialog(null,
                    "There was an error finding the\n"
                  + "image set folders in that directory...\n"
                  + "Please try again!",
                    "Failed Finding Folders", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            for (int i = 0; i < imageSetFolders.size(); i++)
                for (final File fileEntry : imageSetFolders.get(i).listFiles())
                    imageSetFiles.add(fileEntry);
            
            if (imageSetFiles.isEmpty()) {
                JOptionPane.showMessageDialog(null,
                    "The image set folders are empty...\n"
                  + "Please use this program once you\n"
                  + "have organized some files.",
                    "No Images Found", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            for (int i = 0; i < imageSetFiles.size(); i++) {
                fileQueue = new File(
                        sourceDirSrc.getAbsolutePath() + "/" + 
                        imageSetFiles.get(i).getName());
                try {
                    fileQueuePath = Files.copy(
                        imageSetFiles.get(i).toPath(),
                        fileQueue.toPath(),
                        StandardCopyOption.REPLACE_EXISTING);
                    
                    if (fileQueuePath != null) {
                        completedTransfers.add(fileQueue);
                    }
                } catch (IOException ioe) {
                    for (int z = 0; z < completedTransfers.size(); z++)
                        completedTransfers.get(z).delete();
                    JOptionPane.showMessageDialog(null,
                        "There was an error transferring\n"
                      + "your files... Please try again!",
                        "Image Transfer Failed", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            
            for (int i = 0; i < completedTransfers.size(); i++)
                if (!completedTransfers.get(i).exists() ||
                    !completedTransfers.get(i).canRead() ||
                    !completedTransfers.get(i).canWrite()) {
                    for (int z = 0; z < completedTransfers.size(); z++)
                        completedTransfers.get(z).delete();
                    JOptionPane.showMessageDialog(null,
                        "There was an error transferring\n"
                      + "your files... Please try again!",
                        "Image Transfer Failed", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                    
            for (int i = 0; i < imageSetFiles.size(); i++)
                if (imageSetFiles.get(i).delete())
                    System.out.println("Deleted File " + 
                            imageSetFiles.get(i).getName());
                else
                    System.out.println("Failed To Delete File: " + 
                            imageSetFiles.get(i).getName());
            
            //Set A New Source Directory, If Desired
            //If No Source Directory Chosen...
            while (true) {
                sourceDirName = JOptionPane.showInputDialog(null,
                        "Since a source directory wasn't set, please\n"
                      + "choose a name for the image set folders.",
                        "Input A File Name",
                        JOptionPane.PLAIN_MESSAGE);
                if(userInputValid(sourceDirName)) {
                    if(trueFalsePrompt(
                            "Are you sure you want the\nname " 
                           + sourceDirName + "?", "Confirm New Name"))
                        break;
                }
                else
                    JOptionPane.showMessageDialog(null,
                        "Please enter a valid name for the\n"
                      + "image set folders... Please try again!",
                        "Unsuitable Name", JOptionPane.ERROR_MESSAGE);
            }
            
            for (int i = 0; i < imageSetFolders.size(); i++) {
                if (imageSetFolders.get(i).delete())
                    System.out.println("Deleted Folder " + 
                            imageSetFolders.get(i).getName());
                else
                    System.out.println("Failed To Delete Folder: " + 
                            imageSetFolders.get(i).getName());
                
                tempImageSetFolder = new File(destinationDirSrc + "/" + sourceDirName + " - " + i + " Print");
                if(!tempImageSetFolder.exists())
                    if(tempImageSetFolder.mkdir())
                        createdFolders.add(tempImageSetFolder);
            }
            
            writeDataToConfig(configMemory, destinationDirSrc.getAbsolutePath(),
                    sourceDirSrc.getAbsolutePath(), transferStatus);
            
            JOptionPane.showMessageDialog(null,
                    "Transfer complete! The program will now exit.\n"
                  + "Once you have organized all your pictures again,\n"
                  + "just reopen this program! Thanks!", "Transfer Complete!",
                  JOptionPane.PLAIN_MESSAGE);
            System.exit(0);
                
            
        } else if (!configError && configMemory.isEmpty()) {
            boolean userChoice = trueFalsePrompt(
                    "The config is not set up. In order to\n"
                  + "continue, a config must be set up. If you\n"
                  + "have already set up image-set folders,\n"
                  + "please complete config setup and use the\n"
                  + "folders provided by this program instead.\n\n"
                  + "Would you like to set up a config?", "Set Up Config?");
            if (userChoice){
                this.setVisible(false);
                ImageSetPickerUI imageSetPicker = new ImageSetPickerUI();
                imageSetPicker.setVisible(true);
            }
        }

        //ToDo:
            //Finish Write Data To Config
            //Set Up Initial Source (Dialog -> Directory)/"Smart Sources"
                //Line 195
            //Query Source Dir For Future Transfers (Y/N THEN Dialog -> Directory)
                //Line 293
            
        //Check to see if removed files get placed in recycle bin
        //Search for "eventually set up to point back to new directories"
        //Print Failed, Partial, and Full transfers to PAST TRANSFERS section
            //transferStatus = "PARTIAL" on partial or "FAILED" on failed
        //Create Progress Window to keep track of transfers
    }//GEN-LAST:event_bringBackBtnActionPerformed
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeUI().setVisible(true);
            }
        });
    }
    
    private static boolean trueFalsePrompt(String prompt, String title){
        while(true) {
            int userChoice = JOptionPane.showOptionDialog(null, prompt, title,
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, null,
                    new String[]{"No", "Yes"}, "default");
            if (userChoice == 1) {
                return true;
            } else if (userChoice != -1) {
                return false;
            }
        }
    }
    
    private boolean userInputValid(String userInput){
        if(userInput.matches("[/\\\"<>:|?*]"))
            return false;
        else
            return true;
    }
    
    private void writeDataToConfig(ArrayList<String> configMemory,
            String destination, String source, String status){
        if(!configMemory.contains("***PAST TRANSFERS***")){
            configMemory.add("\n\n");
            configMemory.add("***PAST TRANSFERS***");
        }
        configMemory.add(destination 
                    + " >>>TRANSFERRED TO>>> " 
                    + source 
                    + " >>>STATUS: " + status + ">>>");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bringBackBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton resetConfigBtn;
    private javax.swing.JLabel welcomeTextFieldA;
    private javax.swing.JLabel welcomeTextFieldB;
    // End of variables declaration//GEN-END:variables
}
